import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://nhpodzfdebvaizrgmvhb.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ocG9kemZkZWJ2YWl6cmdtdmhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODQzNTAyOTcsImV4cCI6MTk5OTkyNjI5N30.NIKjvN4kO9nqgxm4L1FEtXL8NwG_einyZuNw6jSOTgw')